const IMAGE = {
    ICON_PROFILE :require('../images/profile.png'),
    ICON_MENU :require('../images/menu.png'),
    ICON_BACK : require('../images/back.png'),

    ICON_HOME : require('../images/home.png'),
    ICON_HOME_BLACK : require('../images/home-black.png'),

    ICON_SETTINGS : require('../images/setting.png') ,
    ICON_SETTINGS_BLACK :require('../images/setting-black.png'),
    ICON_LOGOIMAGE : require('../images/react.png'),
    ICON_WISHLIST : require('../images/wishlist.png'),
    ICON_WISHLIST_WHITE: require('../images/wishlist-white.png'),
    ICON_CLASS : require('../images/classroom.png'),
    ICON_CLASS_WHITE:require('../images/classroom-white.png'),
    ICON_TEACHER:require('../images/teacher.png'),
    ICON_TEACHER_WHITE:require('../images/teacher-white.png'),
    ICON_GOAL:require('../images/goal.png'),
    ICON_GOAL_WHITE:require('../images/goal-white.png'),
    ICON_FEATURE:require('../images/Feature.png'),
    ICON_FEATURE_WHITE:require('../images/Feature-white.png'),
    ICON_BRIEF:require('../images/brief.png'),
    ICON_BRIEF_WHITE:require('../images/brief-white.png'),
    ICON_EVENT:require('../images/event.png'),
    ICON_EVENT_WHITE:require('../images/event-white.png'),
    ICON_MEMBER:require('../images/member.png'),
    ICON_MEMBER_WHITE:require('../images/member-white.png'),
    ICON_MEMBER_TOPIC:require('../images/member-topic.png'),
    ICON_MEMBER_LOGO:require('../images/member-logo.png'),
    ICON_EVENT_1:require('../images/event-1.png'),
    ICON_EVENT_2:require('../images/event-2.png'),
    ICON_EVENT_3:require('../images/event-3.png'),
    ICON_FEATURE_1:require('../images/Feature-1.png'),
    ICON_FEATURE_2:require('../images/Feature-2.png'),
    ICON_FEATURE_3:require('../images/Feature-3.png'),
    ICON_FEATURE_4:require('../images/Feature-4.png'),
    ICON_FEATURE_5:require('../images/Feature-5.png'),
    ICON_TEST_1:require('../images/test-1.jpg')
}
export {IMAGE}